Real horas, tarifa, salario
Real horasExtras, valorHoraExtra, totalHorasExtras
Entero i

inicio

Para i <- 1 Hasta 10 Haga

    Escriba "Trabajador ", i

    Escriba "Ingrese horas trabajadas: "
    Lea horas
    
    Escriba "Ingrese tarifa por hora: "
    Lea tarifa

    Si horas > 40 Entonces
        horasExtras <- horas - 40
        valorHoraExtra <- tarifa * 1.5
        totalHorasExtras <- horasExtras * valorHoraExtra
        salario <- (40 * tarifa) + totalHorasExtras
    Sino
        horasExtras <- 0
        valorHoraExtra <- 0
        totalHorasExtras <- 0
        salario <- horas * tarifa
    Fin Si

    Escriba "Salario total: ", salario
    Escriba "Horas extras trabajadas: ", horasExtras
    Escriba "Valor de la hora extra: ", valorHoraExtra
    Escriba "Valor total de horas extras: ", totalHorasExtras

Fin Para

Fin