real base,altura,area
caracter siga


inicio
    siga <- 'S'
    mientras(siga = 'S') o (siga = 's') haga
        escriba "Base ? "
        lea base
        escriba "Altura ? "
        lea altura
        area <- base * altura / 2
        escriba "Al area es ",area
        llamar nueva_linea
        escriba "Desea comtinuar (S/N) ? "
        lea siga
        llamar limpiar_pantalla
   fin mientras
fin
